// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/produk": {
            "get": {
                "description": "Mendapatkan semua produk",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Mendapatkan semua produk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cari produk berdasarkan nama atau deskripsi",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter produk berdasarkan ID kategori",
                        "name": "kategori_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter produk berdasarkan stok minimum",
                        "name": "stok_min",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter produk berdasarkan stok maksimum",
                        "name": "stok_max",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter produk berdasarkan harga minimum",
                        "name": "harga_min",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter produk berdasarkan harga maksimum",
                        "name": "harga_max",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Membuat produk baru dengan upload foto",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Membuat produk baru",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama Produk",
                        "name": "produk_nama",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi Produk",
                        "name": "produk_deskripsi",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Stok Produk",
                        "name": "produk_stok",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Harga Produk",
                        "name": "produk_harga",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID Kategori Produk",
                        "name": "kategori_produk_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID User",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Foto Produk",
                        "name": "produk_foto",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Produk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/produk/image/{filename}": {
            "get": {
                "description": "Mengirim file foto produk",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Serve file foto produk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama file foto",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/produk/statistik": {
            "get": {
                "description": "Mendapatkan statistik produk (total, stok, nilai inventori, dll)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Statistik produk",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/produk/stok-menipis": {
            "get": {
                "description": "Mendapatkan produk dengan stok menipis (\u003c10)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Produk stok menipis",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Produk"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/produk/terbaru": {
            "get": {
                "description": "Mendapatkan daftar produk terbaru",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Produk terbaru",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit produk",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Produk"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/produk/{id}": {
            "get": {
                "description": "Mendapatkan produk berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Mendapatkan produk berdasarkan ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produk ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Update produk termasuk upload foto baru",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Update produk",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produk ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nama Produk",
                        "name": "produk_nama",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi Produk",
                        "name": "produk_deskripsi",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Stok Produk",
                        "name": "produk_stok",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Harga Produk",
                        "name": "produk_harga",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "ID Kategori Produk",
                        "name": "kategori_produk_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "ID User",
                        "name": "user_id",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Foto Produk",
                        "name": "produk_foto",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Produk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Menghapus produk dan foto terkait",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Hapus produk",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produk ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/produk/{id}/stok": {
            "patch": {
                "description": "Mengupdate stok produk (form data)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Produk"
                ],
                "summary": "Update stok produk",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Produk ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Stok baru",
                        "name": "produk_stok",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Produk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Agama": {
            "type": "object",
            "properties": {
                "agama_id": {
                    "type": "integer"
                },
                "agama_nama": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wargas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Warga"
                    }
                }
            }
        },
        "models.KategoriProduk": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "kategori_produk_id": {
                    "type": "integer"
                },
                "kategori_produk_nama": {
                    "type": "string"
                },
                "produks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Produk"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Keluarga": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "keluarga_id": {
                    "type": "integer"
                },
                "keluarga_nama": {
                    "type": "string"
                },
                "keluarga_status": {
                    "type": "string"
                },
                "mutasiKeluargas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MutasiKeluarga"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "wargas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Warga"
                    }
                }
            }
        },
        "models.Level": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "level_id": {
                    "type": "integer"
                },
                "level_kode": {
                    "type": "string"
                },
                "level_nama": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                }
            }
        },
        "models.MutasiKeluarga": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "keluarga": {
                    "$ref": "#/definitions/models.Keluarga"
                },
                "keluarga_id": {
                    "type": "integer"
                },
                "mutasi_keluarga_alasan": {
                    "type": "string"
                },
                "mutasi_keluarga_id": {
                    "type": "integer"
                },
                "mutasi_keluarga_jenis": {
                    "type": "string"
                },
                "mutasi_keluarga_tanggal": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Pekerjaan": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "pekerjaan_id": {
                    "type": "integer"
                },
                "pekerjaan_nama": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wargas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Warga"
                    }
                }
            }
        },
        "models.Produk": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "kategori_produk": {
                    "$ref": "#/definitions/models.KategoriProduk"
                },
                "kategori_produk_id": {
                    "type": "integer"
                },
                "produk_deskripsi": {
                    "type": "string"
                },
                "produk_foto": {
                    "type": "string"
                },
                "produk_harga": {
                    "type": "number"
                },
                "produk_id": {
                    "type": "integer"
                },
                "produk_nama": {
                    "type": "string"
                },
                "produk_stok": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Rumah": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "rumah_alamat": {
                    "type": "string"
                },
                "rumah_id": {
                    "type": "integer"
                },
                "rumah_status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wargas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Warga"
                    }
                }
            }
        },
        "models.TagihanIuran": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "tagihan_iuran": {
                    "type": "string"
                },
                "tagihan_iuran_nominal": {
                    "type": "number"
                },
                "tagihan_iuran_status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "warga": {
                    "$ref": "#/definitions/models.Warga"
                },
                "warga_id": {
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "foto_profile": {
                    "type": "string"
                },
                "level": {
                    "$ref": "#/definitions/models.Level"
                },
                "level_id": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "produk": {
                    "description": "one-to-many produk",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Produk"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "warga": {
                    "description": "one-to-one",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Warga"
                        }
                    ]
                }
            }
        },
        "models.Warga": {
            "type": "object",
            "properties": {
                "agama": {
                    "$ref": "#/definitions/models.Agama"
                },
                "agama_id": {
                    "type": "integer"
                },
                "agamas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Agama"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "keluarga": {
                    "$ref": "#/definitions/models.Keluarga"
                },
                "keluarga_id": {
                    "type": "integer"
                },
                "keluargas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Keluarga"
                    }
                },
                "pekerjaan": {
                    "$ref": "#/definitions/models.Pekerjaan"
                },
                "pekerjaan_id": {
                    "type": "integer"
                },
                "pekerjaans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Pekerjaan"
                    }
                },
                "rumah": {
                    "$ref": "#/definitions/models.Rumah"
                },
                "rumah_id": {
                    "type": "integer"
                },
                "rumahs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Rumah"
                    }
                },
                "tagihanIurans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TagihanIuran"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                },
                "user_id": {
                    "type": "integer"
                },
                "warga_id": {
                    "type": "integer"
                },
                "warga_jenis_kelamin": {
                    "type": "string"
                },
                "warga_nama": {
                    "type": "string"
                },
                "warga_nik": {
                    "type": "string"
                },
                "warga_no_tlp": {
                    "type": "string"
                },
                "warga_status_aktif": {
                    "type": "string"
                },
                "warga_status_hidup": {
                    "type": "string"
                },
                "warga_tanggal_lahir": {
                    "type": "string"
                },
                "warga_tempat_lahir": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
